# Site settings
title: "Omnic Ideas"

# Default header image
header_img:
  url: "assets/img/home-bg.jpg"

comments:
  enabled: false
  disqus_shortname: ""

social_networks:
    twitter: "_g3r4" # Your id without @
    facebook:  # Your URL
    instagram: # Your id
    github: "https://github.com/g3r4"
    dribbble: # Your id
    linkedin: # Your URL
    email: # Your email adress you@yoourDomain.com

# Forms
forms:
    contact:
        getsimpleform_api_token: 
